name: Experiment
on: 
  schedule:
  - cron: '*/5 * * * *'

jobs:
  job1:
    name: Event Generation 
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: [3.8]
    steps:
    - name: Git checkout
      uses: actions/checkout@v2
      with: { ref: develop }
    - name: List files
      run: ls
    - name: Install Python Package
      run: python -m pip install textfsm click
    - name: Run Event Handler
      run: |
        python do.py -t ${{ secrets.SESH_TOKEN }} -u ${{ secrets.USER_ID }}
